[build]
builder = "nixpacks"

[deploy]
startCommand = "cd biomass-prediction-pixelwise/backend && uvicorn app.main_simple:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"

[variables]
PYTHONPATH = "/app/biomass-prediction-pixelwise/backend"